### ISSUE TITLE
In Firefox Nightly, "Actions » Add new server..." in the room directory does not work. Known issue?

### ISSUE THREAD

**Issue by sideshowbarker** [matrix-org/matrix-public-archive#145] opened 2022-11-18 10:23 UTC
I selected "Actions » Add new server..." in the room directory expecting that it’d let me type in the name of different homeserver — but after I select it, nothing happens, and no error is shown in the web UI nor or any messages logged to the terminal

**Comment by MadLittleMods** [comment] 2022-11-18 18:17
@sideshowbarker Do you have JavaScript enabled? Is `/#/add-server` added to the URL at the top?

It should work as described here: https://github.com/matrix-org/matrix-public-archive/pull/87

**Comment by sideshowbarker** [comment] 2022-11-18 18:27
> @sideshowbarker Do you have JavaScript enabled?

I do, yes

> Is `/#/add-server` added to the URL at the top?

Yes, it is

> It should work as described here: #87

OK — thanks

Anyway, I’ll mention now (and should have mentioned before…) that I had only tested in Firefox Nightly.

But I tested just now instead in Firefox 106, and I find that it works as expected in Firefox 106

And also I realize now now, I should have checked the devtools console already — but having done that just now in Firefox Nightly, I see this:

```
Uncaught TypeError: this.dialogNode.showModal is not a function
    showModal http://localhost:3050/js/entry-client-room-directory.es.js:27252
    render http://localhost:3050/js/entry-client-room-directory.es.js:27232
    render http://localhost:3050/js/entry-client-room-directory.es.js:27229
    binding http://localhost:3050/js/entry-client-room-directory.es.js:5274
    update http://localhost:3050/js/entry-client-room-directory.es.js:5064
    _updateFromValue http://localhost:3050/js/entry-client-room-directory.es.js:4989
    emit http://localhost:3050/js/entry-client-room-directory.es.js:11006
    emit http://localhost:3050/js/entry-client-room-directory.es.js:11006
    emitChange http://localhost:3050/js/entry-client-room-directory.es.js:21453
    setOpen http://localhost:3050/js/entry-client-room-directory.es.js:27642
    setShouldShowAddServerModal http://localhost:3050/js/entry-client-room-directory.es.js:27732
    handleAddServerNavigationChange http://localhost:3050/js/entry-client-room-directory.es.js:27862
    emit http://localhost:3050/js/entry-client-room-directory.es.js:1331
    emitIfChanged http://localhost:3050/js/entry-client-room-directory.es.js:21136
    applyPath http://localhost:3050/js/entry-client-room-directory.es.js:21021
    onHomeserverSelectionAction http://localhost:3050/js/entry-client-room-directory.es.js:27767
    onInput http://localhost:3050/js/entry-client-room-directory.es.js:27467
[entry-client-room-directory.es.js:27252:21](http://localhost:3050/js/entry-client-room-directory.es.js)
    showModal http://localhost:3050/js/entry-client-room-directory.es.js:27252
    render http://localhost:3050/js/entry-client-room-directory.es.js:27232
    (Async: FrameRequestCallback)
    render http://localhost:3050/js/entry-client-room-directory.es.js:27229
    binding http://localhost:3050/js/entry-client-room-directory.es.js:5274
    update http://localhost:3050/js/entry-client-room-directory.es.js:5064
    _updateFromValue http://localhost:3050/js/entry-client-room-directory.es.js:4989
    _updateFromValue self-hosted:1494
    emit http://localhost:3050/js/entry-client-room-directory.es.js:11006
    forEach self-hosted:5047
    emit http://localhost:3050/js/entry-client-room-directory.es.js:11006
    emitChange http://localhost:3050/js/entry-client-room-directory.es.js:21453
    setOpen http://localhost:3050/js/entry-client-room-directory.es.js:27642
    setShouldShowAddServerModal http://localhost:3050/js/entry-client-room-directory.es.js:27732
    handleAddServerNavigationChange http://localhost:3050/js/entry-client-room-directory.es.js:27862
    emit http://localhost:3050/js/entry-client-room-directory.es.js:1331
    emitIfChanged http://localhost:3050/js/entry-client-room-directory.es.js:21136
    applyPath http://localhost:3050/js/entry-client-room-directory.es.js:21021
    onHomeserverSelectionAction http://localhost:3050/js/entry-client-room-directory.es.js:27767
    onInput http://localhost:3050/js/entry-client-room-directory.es.js:27467
    receiveMessage resource://gre/actors/SelectChild.jsm:269
    receiveMessage resource://gre/actors/SelectChild.jsm:473

```
…which seems odd, since `HTMLDialogElement»showModal()` is supported in Firefox:

https://developer.mozilla.org/en-US/docs/Web/API/HTMLDialogElement/showModal#browser_compatibility

Anyway, I’ll try troubleshooting it a bit further myself — but if you also have time to look some in Firefox Nightly, that’d be great too.

**Comment by MadLittleMods** [comment] 2023-04-10 21:57
@sideshowbarker Are you still experiencing this problem?

I can't reproduce with Firefox Developer Edition 112.0b9 or Firefox stable 111.0.1

Since our browser compatibility pretty much just assumes the last couple versions of browsers and [`HTMLDialogElement.showModal()`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLDialogElement/showModal#browser_compatibility) has been supported for longer than that, I am leaning towards closing this. Essentially, we don't support browsers which don't have that API available.

Ideally, we'd have some error feedback in the UI on what/why it's not working but will opt for how things are for now ⏩

If there is some nice fix for this, feel free to submit a PR.

**Closed by MadLittleMods** 2023-04-10 21:57 UTC
Labels: T-Defect, A-room-directory

**Comment by sideshowbarker** [comment] 2023-04-13 05:23
> @sideshowbarker Are you still experiencing this problem?

As far as I recall now, I ended up not being able to reproduce it after updating my Nightly. So I probably should have closed it myself at the time — but anyway, thanks for having followed up on it and closed it out
